export const uiLabels = {
  summary: {
    day: "日期",
    money: "资金",
    activeQuests: "进行中任务",
    knownAdventurers: "已知冒险者"
  },
  saveControls: {
    export: "导出存档",
    import: "导入存档",
    reset: "清空存档"
  },
  navigation: {
    workbench: "工作台",
    relief: "救急",
    reference: "查阅",
    settings: "设置",
    encyclopedia: "百科",
    overview: "总览",
    quests: "委托",
    adventurers: "人物",
    intel: "消息板",
    stock: "库存",
    market: "经营",
    log: "日志",
    save: "存档"
  },
  workbench: {
    todayGoalTitle: "今日目标",
    quickPostTitle: "一键发补货委托",
    quickPostDescription: "按当前后厨缺口挂一条补货委托，不必先去市场。",
    inTownTitle: "在镇人物",
    inTownDescription: "谁在店里或镇上；点开看近况。",
    storyTitle: "故事轨",
    postCta: "发布补货委托",
    postCtaWithName: (name: string) => `发布：${name}`,
    waitingCta: "已挂出，进入下一天",
    moreQuests: "其他委托",
    expandStory: "展开全文",
    closeDetail: "关闭",
    emptyInTown: "镇上暂时没有你认识的人。",
    openingWeek: "开张周",
    act1Phase: "据点开张",
    goalKitchenTight: "后厨偏紧：建议补",
    goalWaitingRestock: "补货已在路上，先把日子过下去",
    goalKeepKitchen: "先让后厨不断档",
    goalListenPeople: "后厨稳住了，再听听镇上的人",
    restockProgress: "开张进度：成功补货",
    stableMeals: "稳定供餐",
    suggestPost: "建议发布：",
    waitingFor: "等待返回：",
    suggestAdvanceDay: "进入下一天，看人把货带回来。",
    suggestSeePeople: "点开在镇人物，或展开故事轨。",
    noStockQuest: "当前没有可发布的补货委托。",
    alreadyPosted: "这条补货已经挂出，进入下一天等待结果。",
    questBlocked: "同类委托仍在推进中。",
    insufficientMoney: "资金不够支付建议酬金。",
    costLine: (name: string, reward: number, quantity: number, resourceName: string, days: number) =>
      `${name} · 酬金约 ${reward} 钱 · ${quantity} 单位${resourceName} · 约 ${days} 天`,
    inTownStatus: "在镇上",
    hungryStatus: "缺粮",
    storyHintKitchen: "先让后厨不断档",
    storyHintWaiting: "等人把货带回来",
    storyHintDefault: "店里刚有了火光。"
  },
  panels: {
    overviewTitle: "工作台",
    overviewDescription: "看今日目标、发补货、看在镇的人和故事。",
    reliefTitle: "救急",
    reliefDescription: "市场采购、库存和厨房制作。开张期不是主循环，缺货或现金流卡住时再来这里。",
    todaySummaryTitle: "今天概况",
    todaySummaryDescription: "当前版本先把核心状态集中到这里，后续可接冒险者和建筑摘要。",
    recentQuestsTitle: "最近任务",
    recentQuestsDescription: "这里只显示最近几项，完整列表和发布入口在任务页查看。",
    questsTitle: "任务",
    questsDescription: "这里同时负责发布任务和查看当前委托状态。",
    publishQuestTitle: "发布任务",
    publishQuestDescription: "补货委托为许可收获劳务；调查委托按线索推进。",
    questListTitle: "任务列表",
    questListDescription: "查看当前所有委托及其推进状态。",
    adventurersTitle: "冒险者",
    adventurersDescription: "这里只显示你真正接触或听闻过的人，而不是完整名单。",
    intelTitle: "消息板",
    intelDescription: "自动收录已得到的线索与发现，让这些结果从日志里独立出来。",
    stockTitle: "库存",
    stockDescription: "集中查看已获得的资源、物品和装备。",
    marketTitle: "经营",
    marketDescription: "在市场买卖原料，为饭店菜品定价，并把资源做成可售物品。",
    logTitle: "日志",
    logDescription: "完整记录最近一段时间的每日结果，方便回溯。",
    latestStoriesTitle: "今日动态",
    saveTitle: "存档",
    saveDescription: "管理当前进度的导出、导入与清空。"
  },
  overviewNotes: {
    income: "营业收入",
    pace: "玩法节奏",
    focus: "当前重点",
    incomeValueSuffix: "钱 / 天",
    incomeRetailOnly: "仅靠饭店零售与委托",
    paceValue: "手动进入下一天",
    focusValue: "通过委托补货、市场采购和饭店零售维持现金流"
  },
  form: {
    templateType: "任务类型",
    publishMode: "委托形式",
    statusFilter: "状态筛选",
    natureFilter: "性质筛选",
    adventurerLevelFilter: "认知筛选",
    adventurerStatusFilter: "人物状态",
    adventurerPinnedFilter: "置顶分组",
    reward: "奖励金额",
    stockReward: "劳务酬金",
    intelReward: "悬赏金额",
    quantity: "需求数量",
    quantityLocked: "调查委托不按数量结算",
    createQuest: "发布任务",
    nextDay: "进入下一天"
  },
  questCard: {
    prefix: "任务",
    collect: "目标",
    investigate: "关注",
    result: "结果",
    resultReason: "原因",
    usedItems: "使用道具",
    risk: "风险",
    nature: "性质",
    reward: "悬赏",
    estimatedDuration: "预计总耗时",
    createdDay: "发布于第",
    daySuffix: "天"
  },
  adventurerCard: {
    impression: "印象",
    preference: "倾向",
    personality: "性格",
    currentStatus: "近况",
    lastCompleted: "上次完成",
    motive: "动机",
    pin: "置顶",
    unpin: "取消置顶",
    gift: "赠送",
    askLoadout: "交谈",
    pinnedSection: "置顶人物",
    othersSection: "其他人物"
  },
  intelBoard: {
    leadsTitle: "线索",
    discoveriesTitle: "发现",
    leadsDescription: "调查类任务带回的后续方向与可追踪信息。",
    discoveriesDescription: "异常任务留下的发现记录，后续可接更具体的结果系统。",
    line: "相关主题",
    source: "来源",
    method: "获得方式",
    status: "状态",
    emptyLeads: "还没有整理出新的线索。",
    emptyDiscoveries: "还没有记录到新的发现。"
  },
  stock: {
    empty: "库存还是空的。完成委托或获得物品后，这里才会出现对应分类。"
  },
  market: {
    tradeTitle: "市场",
    tradeDescription: "按市价买卖原料和特定物品。饭店不能卖的品类应走这里。",
    innTitle: "饭店",
    innDescription: "为食物定价、制作菜品，经营来店冒险者的零售。",
    shopTitle: "定价",
    shopDescription: "为食物类菜品设置售价。冒险者来店时会按你的定价购买。",
    craftTitle: "厨房制作",
    craftDescription: "把任务带回的原料做成可售菜品。",
    unitPrice: (price: number) => `市价 ${price} 钱`,
    buyPrice: (price: number) => `买入 ${price} 钱`,
    sellPrice: (price: number) => `卖出 ${price} 钱`,
    marketStock: (amount: number) => `市场 ${amount}`,
    tradeHint: (buyPrice: number, sellPrice: number, marketAmount: number, playerAmount: number) =>
      `${uiLabels.market.buyPrice(buyPrice)} · ${uiLabels.market.sellPrice(sellPrice)} · ${uiLabels.market.marketStock(marketAmount)} · ${uiLabels.market.owned(playerAmount)}`,
    owned: (amount: number) => `持有 ${amount}`,
    batchLabel: (size: number) => `x${size}`,
    batchGroupLabel: (sectionTitle: string) => `${sectionTitle}批量数量`,
    buyAction: (size: number) => `买 ${size}`,
    sellAction: (size: number) => `卖 ${size}`,
    shopHint: (marketPrice: number, amount: number) => `参考市价 ${marketPrice} 钱 · 库存 ${amount}`,
    shopPriceLabel: (name: string) => `${name} 售价`,
    savePrice: "保存售价",
    craftInputs: (text: string) => `需要：${text}`,
    craftAction: (size: number) => (size === 1 ? "制作" : `制作 x${size}`)
  },
  bailout: {
    titlePlaceholder: "资助",
    decline: "暂不接受",
    accept: "收下资助",
    acceptAmount: (amount: number) => `收下 ${amount} 钱`,
    amountLabel: (amount: number) => `资助金额：${amount} 钱`
  },
  stockCategories: {
    material: "原料",
    food: "食物",
    product: "成品",
    equipment: "装备",
    treasure: "宝物",
    misc: "其他"
  },
  itemCategories: {
    food: "食物",
    consumable: "消耗品",
    product: "成品",
    misc: "其他"
  },
  equipmentSlots: {
    weapon: "武器",
    shield: "盾",
    helmet: "头盔",
    armor: "护甲",
    legArmor: "腿甲",
    boots: "靴子",
    accessory: "饰品",
    tool: "工具"
  },
  effectTargets: {
    physique: "体魄",
    survival: "生存",
    exploration: "探索",
    observation: "观察",
    combat: "战斗",
    danger: "危险",
    challenge: "挑战",
    durationPressure: "耗时压力",
    uncertainty: "不确定",
    investigationComplexity: "调查复杂度",
    reportDifficulty: "报告难度",
    stability: "稳定",
    risk: "风险"
  },
  gifting: {
    title: "赠送物品",
    close: "关闭",
    confirm: "确定赠送",
    gift: "赠送",
    noAvailableItem: "目前没有可赠送的物品。",
    noAvailableAdventurer: "目前没有可赠送的城镇内冒险者。",
    itemModeHelp: (name: string) => `选择要赠送给 ${name} 的物品。多选时会逐件判定是否接受。`,
    adventurerModeHelp: (itemName: string, amount: number) => `选择要赠送 ${itemName} 的冒险者。当前可用 ${amount} 个，多选时会逐人判定。`,
    carriedCount: (count: number) => `携带 ${count} 件`
  },
  loadout: {
    title: "交谈",
    close: "关闭",
    equipmentTitle: "全身装备",
    carriedTitle: "随身物品",
    activeBuffTitle: "状态增益",
    emptyActiveBuffs: "当前没有持续中的食物增益。",
    buffRemaining: "剩余",
    moneyTitle: "携带金钱",
    dialogueTitle: "谈话",
    emptyEquipment: "暂未看到装备。",
    emptySlot: "空着",
    emptyCarriedItems: "他身上没有你送出的可用物品。",
    hiddenMoney: "关系还没到会主动说钱袋情况的程度。",
    hiddenCarriedItems: "关系还没到能问清全部随身物品的程度。",
    itemClauseHidden: "包里的东西我还不能一项项说给你听。",
    itemClauseEmpty: "身上没带你送出的可用东西。",
    itemClauseWithItems: (itemList: string) => `现在带着 ${itemList}。`,
    equipmentClauseEmpty: "装备这边看不太出来有什么。",
    equipmentClauseWithItems: (equipmentList: string) => `装备是 ${equipmentList}。`,
    moneyClauseHidden: "钱有多少，我还不能跟你细说。",
    moneyClauseWithAmount: (amount: string) => `身上带着 ${amount}。`,
    renameAction: (currentName: string) => `更改「${currentName}」的自定义名称`,
    renameHintPlain: (shortName: string) => `点击为「${shortName}」设置自定义名称`,
    renameHintCustom: (fullName: string, shortName: string) => `自定义名称｜原名：${fullName}（${shortName}）`,
    renameTitle: "装备自定义名称",
    renameDescription: "给这件装备起一个你更容易记住的名字。留空会恢复为默认简称。",
    renameFormatHelp: "支持 & 颜色/样式代码（与 Minecraft/Bukkit 相同）：&c 红、&e 黄、&l 粗体、&o 斜体、&n 下划线、&#RRGGBB 自定义色、&r 重置。代码本身不计入字数。",
    renamePlaceholder: "例如：&6旧城&7巡夜&9圆盾",
    renameVisibleLength: (current: number, max: number) => `可见字数 ${current} / ${max}`,
    renamePreviewEmpty: "预览会显示在这里。",
    renameSave: "保存",
    renameCancel: "取消",
    renameSaved: "装备名称已更新。",
    renameCleared: "已恢复默认简称。",
    shelfLife: "还可随行",
    uses: "可用次数",
    amount: "数量",
    moneySuffix: "钱",
    questSuffix: "次任务",
    useSuffix: "次",
    acquiredDay: "获得于第",
    daySuffix: "天",
    unknownAdventurer: "没有找到这名冒险者。"
  }
} as const;
